name: Release hungergames.exe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - name: Copy settings file
      uses: canastro/copy-file-action@master
      with:
        source: "src/settings.txt"
        target: "src/dist/windows/settings.txt"
    - name: Create "dependencies" directory
      run: mkdir -p src/dist/windows/dependencies
    - name: Copy Chrome Driver
      uses: canastro/copy-file-action@master
      with:
        source: "src/dependencies/chromedriver.exe"
        target: "src/dist/windows/dependencies/chromedriver.exe"

    - uses: actions/upload-artifact@v2
      with:
        name: hungergames.zip
        path: src/dist/windows # or path/to/artifact