name: Release hungergames.exe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - name: Copy settings file
      uses: canastro/copy-file-action@master
      with:
        source: "src/settings.txt"
        target: "src/dist/windows/settings.txt"
    - name: Copy README.md file
      uses: canastro/copy-file-action@master
      with:
        source: "src/README.md"
        target: "src/dist/windows/README.txt"
    - name: Create "dependencies" directory
      run: mkdir -p src/dist/windows/dependencies
    - name: Copy Chrome Driver
      uses: canastro/copy-file-action@master
      with:
        source: "src/dependencies/chromedriver.exe"
        target: "src/dist/windows/dependencies/chromedriver.exe"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hungergames
        path: src/dist/windows # or path/to/artifact
    - name: Create Github Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
    - name: Upload asset to github Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: /src/dist/windows/hungergames
        asset_name: hungergames-v${{ github.run_number }}.zip
        asset_content_type: application/zip